### ISSUE TITLE
PhoneNumberMetadata.xml resource not found

### ISSUE THREAD

**Issue by chtombre** [twcclegg/libphonenumber-csharp#155]
When using latest libphonenumber-csharp v8.12.51, I get error:

```
PhoneNumberMetadata.xml resource not found
at PhoneNumbers.BuildMetadataFromXml.GetStream(String name, Assembly asm, Boolean nameSuffix)
at PhoneNumbers.PhoneNumberUtil..ctor(String baseFileLocation, Assembly asm, Dictionary`2 countryCallingCodeToRegionCodeMap)
at PhoneNumbers.PhoneNumberUtil.GetInstance(String baseFileLocation, Dictionary`2 countryCallingCodeToRegionCodeMap)
at PhoneNumbers.PhoneNumberUtil.GetInstance()
```

Downgrade to 8.12.50 resolve the issue.

**Comment by twcclegg** [comment]
Thank you for the report, things should be fixed in v8.12.51.1. The way in which git handles file casing can be frustrating at times.
